//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCeCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainSlider
    {
        public int MainSliderID { get; set; }
        public string ImageUrl { get; set; }
        public string AltText { get; set; }
        public string OfferTag { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string BtnText { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
